### ISSUE TITLE
convolution requires multiple vectorization passes.

### ISSUE THREAD

**Issue by gysit** [google/iree-llvm-sandbox#102]
At the moment, we need to call vectorization twice when optimizing convolution 2d. In particular, we have to vectorize the pad tensor operations in the second pass:
```
Vectorize(fun_name, "", vectorize_paddings=False) + \
Vectorize(fun_name, "") + \
```

If we run vectorization only once the ir after vectorization contains unnecessary conversions from vector to tensor that require buffer allocations afterwards. The following gist shows the ir before and after vectorization:
https://gist.github.com/gysit/b3440f4cf821e62f4c44ec44c4bd8e26

The solution is to switch to multiple vectorization passes:
https://gist.github.com/gysit/d471ff1621db0250fa77ba74bca9d0f7
The ir after the second vectorization pass is much cleaner and also significantly faster (25 vs 90gflops).

Initial investigations show that the canonicalizations running between the two vectorization passes enable a better vectorization of the pad tensor operations. The following IR shows the code right after applying the vectorization patterns and before running canonicalization and compares it to the code after running the canonicalizations:
https://gist.github.com/gysit/c56deb5d5ab0004d906f888d343f1fe9

We observe that the canonicalizations merge the extract slice operations after the padding with the corresponding transfer_read operations.

**Comment by ThomasRaoux** [comment]
The difference seems to come from the fact than in the first case the rank of the transfer_read coming from the conv is smaller and blocks the store to load forwarding:
```
%18 = vector.transfer_write %17, %1[%c0, %c0, %c0, %c0] {in_bounds = [true, true, true, true]} : vector<1x1x8x8xf32>, tensor<1x1x8x8xf32>
%21 = vector.transfer_read %18[%c0, %c0, %c0, %c0], %cst_0 {in_bounds = [true, true, true]} : tensor<1x1x8x8xf32>, vector<1x8x8xf32>
```
This doesn't canonicalize even though the ops should obviously cancel each other.

In the second case the transfer_read returns a 4D vector before the second vectorization pass:
```
%19 = vector.transfer_read %17[%c0, %c0, %c0, %c0], %cst_0 {in_bounds = [true, true, true]} : tensor<1x1x8x8xf32>, vector<1x8x8xf32>
```
I'm guessing this is because the transfer_read has been combined with `tensor.extract_slice`

It is hard to tell which is the canonical representation of `vector.transfer_read`. The obvious solution would be to make our canonicalization/optimization for store to load forwarding be more general and robust. This case would be trivial to handle since the blocking part is just a unit dim so we could have a canonicalize for transfer_read handling than (right now store to load forwarind is in transfer_read folding).

No matter what I do think we should be able to simplify the IR in the first case.

**Comment by ThomasRaoux** [comment]
Another thought, maybe what we miss is more simplification of the IR and just removing the unit dimensions we have in the vectors, that would allow the folding to kick in. 

No matter what I feel like the IR of the first case should get simplified before getting to bufferization.

**Comment by ThomasRaoux** [comment]
one solution for instance would be to call those patterns:
`populateCastAwayVectorLeadingOneDimPatterns`

**Comment by gysit** [comment]
Thanks for the hints. 

I did dig a bit deeper yesterday and found the following workarounds:
- Add the TransferRead and TransferWrite canonicalization patterns to the pattern set used by vectorization
- Either, run the PadTensorOp vectorization in a separate step after vectorizing the named operations
- Or, remove the `GenericPadTensorOpVectorizationPattern` from the pattern set.

The later seemed to work for matrix multiplication as well but I suspect there will be cases where we need it. Will also have a look at `populateCastAwayVectorLeadingOneDimPatterns` but it seems the existing pattern set does well. We just need to run them in the right order TM. 

Last point is that there is quite a bit of runtime variance. So there may be potential to further improve performance.

**Comment by nicolasvasilache** [comment]
Nice findings!

I expect we'll be in a much better position wrt structuring and ordering
pattern sets in a few weeks.
